version: '3.8'

services:
  backend:
    container_name: django-backend
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
    volumes:
      - ./backend:/app
    expose:
      - "8000"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend/media:/app/media
    depends_on:
      - backend
      - frontend