version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: django-backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
    volumes:
      - ./backend:/app
      - ./backend/media:/app/media
    expose:
      - "8000"
    command: >
      gunicorn ecommerce.wsgi:application
      --bind 0.0.0.0:8000
      --workers 3

  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html
      - ./backend/media:/app/media
    depends_on:
      - backend
